train:
  _target_: src.datasets.MNISTDataset
  name: "train"
  limit: 5
  istance_transforms: ${transforms.instance_transforms.inference}
test:
  _target_: src.datasets.MNISTDataset
  name: "test"
  limit: 5
  istance_transforms: ${transforms.instance_transforms.inference}